import Link from "next/link";

export function ShowcaseFooter({ presetName }: { presetName: string }) {
  return (
    <footer className="mt-12 border-t border-zinc-200 dark:border-zinc-800 pt-6 text-sm text-zinc-600 dark:text-zinc-400">
      <p className="mb-2">
        This page is generated by the OCEAN stdlib preset{" "}
        <code className="font-mono text-emerald-700 dark:text-emerald-400">{presetName}</code>.
      </p>
      <p className="mb-2">Install the CLI to run this pipeline against your own data:</p>
      <pre className="bg-zinc-50 dark:bg-zinc-900 p-3 rounded-md text-xs font-mono">
{`pip install latentocean-ocean
ocean run ${presetName}`}
      </pre>
      <p className="mt-4">
        Read the handbook for the full language reference:{" "}
        <Link href="/handbook" className="text-emerald-700 dark:text-emerald-400 hover:underline">
          /handbook
        </Link>
      </p>
    </footer>
  );
}
