"""Build / validate the OCEAN Handbook.

Runs all seven validators against `docs/handbook/`:

  1. parse          — every chapter parses
  2. skeleton       — required sections + frontmatter present
  3. snippets       — every runnable OCEAN block compiles
  4. corpora        — every runnable block uses a sanctioned toy corpus
  5. glossary       — every italicized term has a glossary entry
  6. exercises      — every exercise has a solution in Appendix F
  7. voice          — no first-person, no projections / finance acronyms

Usage:
    python -m scripts.handbook.build --check
    python -m scripts.handbook.build --emit-content frontend/lib/handbook-content.ts
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from scripts.handbook.parse_chapter import ParseChapterError, parse_chapter
from scripts.handbook.validate_corpora import validate_corpora
from scripts.handbook.validate_exercises import validate_exercises
from scripts.handbook.validate_glossary import validate_glossary
from scripts.handbook.validate_skeleton import validate_skeleton
from scripts.handbook.validate_snippets import validate_snippets
from scripts.handbook.validate_voice import validate_voice

REPO_ROOT = Path(__file__).resolve().parents[2]
HANDBOOK_DIR = REPO_ROOT / "docs" / "handbook"
SOLUTIONS_FILENAME = "app-f-exercise-solutions.md"
GLOSSARY_FILENAME = "app-d-glossary.md"


def _discover_chapter_paths(handbook_dir: Path) -> list[Path]:
    return sorted(p for p in handbook_dir.glob("*.md") if p.is_file())


def _emit_error(msg: str) -> None:
    print(f"ERROR: {msg}")


def run_check(handbook_dir: Path) -> int:
    """Return number of errors discovered."""
    errors_total = 0

    chapter_paths = _discover_chapter_paths(handbook_dir)
    if not chapter_paths:
        _emit_error(f"no markdown files found in {handbook_dir}")
        return 1

    # 1. parse
    chapters = []
    for cp in chapter_paths:
        try:
            chapters.append(parse_chapter(cp))
        except ParseChapterError as exc:
            _emit_error(str(exc))
            errors_total += 1
    if not chapters:
        return errors_total

    # 2. skeleton
    for chap in chapters:
        for err in validate_skeleton(chap):
            _emit_error(err)
            errors_total += 1

    # 3. snippets
    for chap in chapters:
        try:
            for err in validate_snippets(chap):
                _emit_error(err)
                errors_total += 1
        except Exception as exc:  # noqa: BLE001 - never crash the build
            _emit_error(f"{chap.path}: snippet validator crashed: {exc}")
            errors_total += 1

    # 4. corpora
    for chap in chapters:
        for err in validate_corpora(chap):
            _emit_error(err)
            errors_total += 1

    # 5. glossary
    glossary_path = handbook_dir / GLOSSARY_FILENAME
    for err in validate_glossary(chapters, glossary_path):
        _emit_error(err)
        errors_total += 1

    # 6. exercises
    solutions_path = handbook_dir / SOLUTIONS_FILENAME
    for err in validate_exercises(chapters, solutions_path):
        _emit_error(err)
        errors_total += 1

    # 7. voice
    for chap in chapters:
        for err in validate_voice(chap):
            _emit_error(err)
            errors_total += 1

    return errors_total


def run_emit_content(handbook_dir: Path, out_path: Path) -> int:
    chapter_paths = _discover_chapter_paths(handbook_dir)
    entries = []
    for cp in chapter_paths:
        try:
            chap = parse_chapter(cp)
        except ParseChapterError as exc:
            _emit_error(str(exc))
            return 1
        entries.append(
            {
                "slug": chap.frontmatter.get("slug"),
                "number": chap.frontmatter.get("number"),
                "title": chap.frontmatter.get("title"),
                "promise": chap.frontmatter.get("promise"),
                "status": chap.frontmatter.get("status"),
                "path": str(cp.relative_to(REPO_ROOT)).replace("\\", "/"),
                "body": chap.body,
            }
        )
    payload = json.dumps(entries, indent=2)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "// Generated by scripts/handbook/build.py — do not edit by hand.\n"
        f"export const handbookContent = {payload} as const;\n",
        encoding="utf-8",
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="scripts.handbook.build")
    parser.add_argument("--check", action="store_true", help="validate and exit 1 on errors")
    parser.add_argument(
        "--emit-content",
        metavar="PATH",
        help="emit a generated TS module summarising chapters",
    )
    parser.add_argument(
        "--handbook-dir",
        default=str(HANDBOOK_DIR),
        help="override the handbook directory (default: docs/handbook)",
    )
    args = parser.parse_args(argv)
    hb_dir = Path(args.handbook_dir)

    if args.check:
        errors = run_check(hb_dir)
        if errors:
            print(f"\n{errors} error(s) found.", file=sys.stderr)
            return 1
        print("OK")
        return 0

    if args.emit_content:
        return run_emit_content(hb_dir, Path(args.emit_content))

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
